language: php

dist: trusty

sudo: false

cache:
    directories:
        - ~/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.2
    - php: 7.2
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

install:
    - composer update --no-interaction --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict
    - composer fix-style
    - composer analyse
    - composer test